services:
  spark-notebook:
    image: jupyter/pyspark-notebook:spark-3.4.1
    container_name: spark-notebook
    ports:
      - "${JUPYTER_PORT}:8888"
      - "${SPARK_UI_PORT}:4040"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./scripts:/home/jovyan/work/scripts
      - ./evidences:/home/jovyan/work/evidences
    env_file:
      - .env
    environment:
      SPARK_LOCAL_IP: 0.0.0.0
      PYSPARK_PYTHON: python
      JUPYTER_ENABLE_LAB: "yes"
    working_dir: /home/jovyan/work